# Generated by Django 3.1.7 on 2021-07-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210721_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gnere',
        ),
        migrations.AddField(
            model_name='game',
            name='gnere',
            field=models.ManyToManyField(to='game.Gnere'),
        ),
    ]
