# Generated by Django 3.1.7 on 2021-07-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210721_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gnere',
            new_name='Genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gnere',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='game.Genre'),
        ),
    ]
