# Generated by Django 3.1.7 on 2021-07-24 11:54

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210719_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=user.models.user_image_path),
        ),
    ]
