# Generated by Django 3.1.7 on 2021-07-24 17:35

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210724_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=user.models.user_image_path),
        ),
    ]
