name: pipeline
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: set up python environment 
              uses: actions/setup-python@v5
              with:
                python-version: 3.9
            - name: install requirements
              run: pip install --quiet -r requirements.txt
            - name: lint
              run: |
                cd app
                flake8 --ignore=E501,E231 *.py
                pylint --disable=C0301 *.py
    test:
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - uses: actions/checkout@v4
            - name: set up python environment 
              uses: actions/setup-python@v5
              with:
                python-version: 3.9
            - name: install requirements
              run: pip install --quiet -r requirements.txt
            - name: test
              run: |
                cd app
                python manage.py test