name: pipeline
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Docker Compose
              run: |
                docker-compose build
                docker-compose up -d
            - name: lint with docker
              run: docker-compose run app sh -c "flake8"
            # - name: lint
            #   run: |
            #     cd app
            #     flake8 --ignore=E501,E231 *.py
            #     pylint --disable=C0301 --disable=C0326 *.py
            #     shopt -s globstar
            #     pylint --load-plugins pylint_django --django-settings-module=app.settings **/*.py
    test:
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Docker Compose
              run: |
                docker-compose build
                docker-compose up -d
            - name: test
              run: |
                docker-compose run app sh -c "python manage.py test"